### ISSUE TITLE
Copyright section is outdated

### ISSUE THREAD

**Issue by maurezen** [jcabi/jcabi-velocity#2]
Copyright sections still feature 2014 as a year.

**Comment by dmarkov** [comment]
I'll find a developer for the task soon...

**Comment by dmarkov** [comment]
@romankisilenko please go ahead, it's your task now, keep [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions you may have; This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by dmarkov** [comment]
@maurezen thank you for reporting this, I added 15 mins to your acc, transaction `50045858`

**Comment by RomanKisilenko** [comment]
@maurezen PR reviewed and closed, please close this issue.

**Comment by dmarkov** [comment]
@romankisilenko you're working with this issue for 15 days already

-30 added to your rating, at the moment it is: +360

**Comment by RomanKisilenko** [comment]
@maurezen Please close this issue as PR was already reviewed and closed.

**Comment by maurezen** [comment]
@RomanKisilenko oh, sorry about that, the first notification got lost. Closing.

**Comment by dmarkov** [comment]
@romankisilenko I just added **30 mins** to your account, many thanks for your contribution..; +30 added to your rating, current score is: +390
